module.exports=(req,res,next)=>{
    try{
        if(!(req.session&&req.session.user)){
            next()
        }
        else{
            res.redirect('/');
        }
    }
    catch(err){
        console.log(err);
    }
}